(()=>{
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const header=$('[data-header]'),bar=$('.progress i');
function onScroll(){const y=scrollY,d=document.documentElement.scrollHeight-innerHeight;header.classList.toggle('scrolled',y>10);bar.style.transform=`scaleX(${d>0?y/d:0})`}onScroll();addEventListener('scroll',onScroll,{passive:true});
const menu=$('.menu'),nav=$('.nav');function closeMenu(){menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});$$('.nav a').forEach(a=>a.addEventListener('click',closeMenu));addEventListener('resize',()=>{if(innerWidth>900)closeMenu()});
const reveal=$$('[data-reveal]');if(matchMedia('(prefers-reduced-motion: reduce)').matches||!('IntersectionObserver'in window))reveal.forEach(x=>x.classList.add('show'));else{const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -4%'});reveal.forEach(x=>io.observe(x))}
const calls={urgent:{meta:'Eingehender Anruf · technischer Notdienst',title:'„Unsere Kühlung ist ausgefallen. Der Betrieb startet um sechs.“',urgency:'sofort',wait:false,caller:'Produktionsstandort, Kühlung seit 20 Minuten ausgefallen, Ware möglicherweise gefährdet.',bot:'Erfasst Standort, Rückrufnummer, betroffene Anlage, Auswirkung und Zugang.',decision:'Bereitschaft jetzt informieren',copy:'Mit Grund, Kontaktdaten und strukturierter Zusammenfassung.',tag:'eskalieren'},wait:{meta:'Eingehender Anruf · Terminorganisation',title:'„Ich möchte den Termin morgen verschieben.“',urgency:'später',wait:true,caller:'Bestandskunde, Auftrag bekannt, Rückruf am nächsten Vormittag gewünscht.',bot:'Erfasst Name, Rückrufnummer, Auftragsbezug und gewünschtes Zeitfenster.',decision:'Für das Büro vormerken',copy:'Vollständige Übergabe für den nächsten Arbeitstag.',tag:'nicht stören'}};
$$('[data-call]').forEach(tab=>tab.addEventListener('click',()=>{const d=calls[tab.dataset.call];$$('[data-call]').forEach(t=>{const active=t===tab;t.classList.toggle('active',active);t.setAttribute('aria-selected',String(active))});$('[data-call-meta]').textContent=d.meta;$('[data-call-title]').textContent=d.title;$('[data-urgency]').textContent=d.urgency;$('[data-urgency]').classList.toggle('wait',d.wait);$('[data-caller]').textContent=d.caller;$('[data-bot]').textContent=d.bot;$('[data-decision-title]').textContent=d.decision;$('[data-decision-copy]').textContent=d.copy;$('[data-decision-tag]').textContent=d.tag;const box=$('[data-decision]');box.classList.toggle('urgent',!d.wait);box.classList.toggle('wait',d.wait)}));
$$('details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)$$('details[open]').forEach(o=>{if(o!==d)o.open=false})}));
const form=$('#form'),success=$('.success'),error=$('.error');form.addEventListener('submit',e=>{e.preventDefault();let ok=true;$$('[required]',form).forEach(f=>{const valid=f.checkValidity()&&f.value.trim();f.classList.toggle('invalid',!valid);if(!valid)ok=false});if(!ok){error.textContent='Bitte füllen Sie alle Pflichtfelder vollständig aus.';$('.invalid',form)?.focus();return}error.textContent='';form.hidden=true;success.hidden=false});$$('input,select,textarea',form).forEach(f=>['input','change'].forEach(ev=>f.addEventListener(ev,()=>f.classList.remove('invalid'))));$('.reset').addEventListener('click',()=>{form.reset();form.hidden=false;success.hidden=true;$('input',form).focus()});$('[data-year]').textContent=new Date().getFullYear();
})();
